# Generated by Django 2.2.1 on 2019-06-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvInfo',
            fields=[
                ('e_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('p_id', models.BigIntegerField(verbose_name='所属项目')),
                ('e_name', models.CharField(max_length=50, verbose_name='环境名称')),
                ('create_user', models.CharField(max_length=50, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '环境信息',
                'verbose_name_plural': '环境信息',
                'db_table': 'env_info',
            },
        ),
    ]
