# Generated by Django 2.2.1 on 2019-06-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20190606_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinfo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
